### PR TITLE
LitMotion v2.0

### PR DESCRIPTION
**Pull request by AnnulusGames**
We have started work on releasing a new version of LitMotion, which will include performance improvements, Sequence support, visual editor support, and API improvements (including breaking changes). You can see the work in this branch.

### CODE REVIEW

**Comment by AnnulusGames** [comment]
In order to build a new Sequence package, we have closed PR #122, where work was stalled. We will create a new PR soon.

**Comment by Akeit0** [comment]
Please make `LoopType.Yoyo` behave like yoyo.

**Comment by Niek352** [comment]
If u can plz add shortcut method for, 
```
if(motion.IsActive)
{
    motion.Cancel()
}
```
```
motion.IfActiveCancel()
```

**Comment by FirsovAndrey** [comment]
Please add method WithOnComplete() and others without closures like BindWithState()

**Comment by aprius** [comment]
If the tween first launches the animation and it doesn't work properly the next time it starts up again, maybe there needs to be a method to initialize the system. Currently I'm doing this manually by running an empty tween when I launch the game.

But it would be nice if there was a dedicated method for that and it would launch automatically

image

**Comment by AnnulusGames** [comment]
This is strange because I have never seen this in my environment. I will investigate it anyway.

**Comment by laicasaane** [comment]
Will version 2.0 address this issue on ergonomics?
https://github.com/AnnulusGames/LitMotion/issues/133

**Comment by AnnulusGames** [comment]
> Will version 2.0 address this issue on ergonomics? #133

By design, LitMotion does not allow you to get the start value using a getter, so you must explicitly pass the start value. This will remain the same in v2. (There was a proposal in the forum to omit the start value, but this would complicate the implementation of the extension method and make the behavior unclear, so I am not currently adopting it.)

Regarding automatic rewriting of animations, it may be possible to achieve this by adding an extension to AddTo(Object, LinkBehavior). I will consider this.

**Comment by AnnulusGames** [comment]
> Hi, basing on this [commit](https://github.com/AnnulusGames/LitMotion/pull/138/commits/3d6f1c145208aa79e4ab80736f632a086fcc3eba), I'm guessing [manual updating of motions](https://annulusgames.github.io/LitMotion/articles/en/updating-motion-manually.html) is being removed? Is there any reason for this?
> 
> I know there isn't much use for it for single player games but in multiplayer, being able to manually control the timing of simulation is important, especially in the cases of prediction and rollback.

I plan to add a new implementation of `ManualMotionDispatcher` (the name may change) by the v2 release.

**Comment by AnnulusGames** [comment]
v2.0 has been merged and will be released soon!

**Comment by Rotanticu** [comment]
Can the damper function be added? For handling animations that often need to be interrupted, damper is a better choice than Tween.
Here are some introductions I found
https://theorangeduck.com/page/fitting-code-driven-displacement
https://theorangeduck.com/page/code-vs-data-driven-displacement

I have tried to implement a version before, but I couldn't achieve a good integration between Damp and the existing Tween Perhaps you can do better
https://github.com/Rotanticu/LitDamper

**Comment by AnnulusGames** [comment]
With the release of v2, this issue has been closed. Please create a new issue.

**Pull request merged**
